### ISSUE TITLE
QGIS 3.x compatibility needed

### ISSUE THREAD

**Issue by Andrey-VI** [3nids/plaingeometryeditor#5]
QGIS version 3 compatibility needed.
Very useful plugin!

**Comment by zezzagio** [comment]
> QGIS version 3 compatibility needed.
> Very useful plugin!

The last commit is very old; I think the project is abandoned (I didn't ask, though).

I managed to get it work in QGis 3 (it seems to work, at least, I didn't test it completely). You may try it, if you are brave enough (I'm not a programmer; not a Python programmer, above all.) It's in my fork.

I don't know if it worths to be merged with the original project; I don't know how to do it, either.

Ciao.

**Comment by 3nids** [comment]
I would be happy to port it if I get any support for this!
It should be about 1 day of work.

**Comment by zezzagio** [comment]
> I would be happy to port it if I get any support for this!
> It should be about 1 day of work.

Actually a little more, for me, for I don't know Python (and a lot of other things). I solved almost anything, though; at least, so seems to me: it shows the WKT and WKB code, switching between the two, copy and paste work... strange things sometimes happen  when resizing the dialog, and I wasn't able to put the icon in the tool bar... and there may well be other problems I have not intercepted yet.

You may find the code here:

https://github.com/zezzagio/plaingeometryeditor.git

Ciao.

**Comment by 3nids** [comment]
just saying I cannot not work for free at the moment on this plugin.
I would be happy to integrate your port (feel free to pull a request) or to provide an offer for porting it.

**Comment by zezzagio** [comment]
Git and github are among the other things that I don't know. I'll take a look in this weekend, trying to fix the last things, too.

I can't provide you money support of any type, but I can work for free, under supervision.

Ciao.

**Comment by 3nids** [comment]
ok, thanks for looking into it, I'll be able to review your code!

**Comment by FERRATON** [comment]
any news?
I confirm that this plugin is interesting for the detection of geometry errors

**Comment by zezzagio** [comment]
> any news?
> I confirm that this plugin is interesting for the detection of geometry errors

Almost done; the options setting still does not work, but otherwise it's okay.

I sent a pull request to the author; he should review my code and decide whether to join it to the main distribution.

In the meantime, you can find it here: https://github.com/zezzagio/plaingeometryeditor

Ciao.

**Comment by zezzagio** [comment]
> Thank you.
> Indeed, On loading I have the message
> NameError: name 'SettingManager' is not defined
> But the console displays
> Plain Geometry Editor loaded (plaingeometryeditor package)
> 
> But I can't find the launch icon or an item in the QGIS menus?
> (QGIS 3.4.2)

Yes, of course, sorry.

I didn't build a package, yet.  Assuming you have all the needed tools installed (git, pyqt5, and some other stuff in Linux; Msys, git, pyqt5 and a lot of other stuff in Windows), this works for me:

$ git clone https://github.com/zezzagio/plaingeometryeditor.git plaingeometryeditor
$ cd plaingeometryeditor
$ git submodule update --init --recursive
$ make deploy

This should copy all the files in your user plugins folder. Opening QGis, the plugin should be installed.

Or you may add the submodule (the missed 'SettingManager') by hand, copying the module:

https://github.com/opengisch/qgissettingmanager

in the qgissettingmanager folder of the plaingeometryeditor plugin. This should fix the problem, provided you have compiled the resources and the ui file (resources.qrc and ui_geomeditor.ui)

I'll try and provide a package, as soon as I can.

Ciao.

**Comment by 3nids** [comment]
it is now released.
many thanks @zezzagio for your work, and sorry for the delay.
